title: Ling Zhou
email: lingzhou14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ling Zhou - Blog - Resume.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lingmaozhou.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ling Zhou
author-pic: ling_headshot.JPG
about-author: Hi! I'm Ling. <br/> <br/> I'm a strategy consultant and a 2019 Wellesley grad living in New York City. <br/> <br/> I grew up in Atlanta, but I haven't complained too much about giving up my horses and sweet tea for the city that never sleeps. When I'm not traveling for work, you can find me listening to podcasts in my apartment, running along the East River, or trying new foods all around NYC. <br/> <br/> This place is for me to organize my thoughts and share everything from my reading list to restaurant recommendations. Please feel free to message me to get in touch! <br/> <br/>

# Contact links
email: lingzhou14@gmail.com
linkedin: lingmaozhou
facebook: ling.zhou14
instagram: ling_zhou

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
