title: My personal blog - Ling Zhou
email: lingzhou14@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ling Zhou - Blog - Resume.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ling Zhou
author-pic: ling_headshot.jpg
about-author: My name is Ling! I'll write more here later...

# Contact links
email: lingzhou@gmail.com
linkedin: lingzhou14
facebook: ling.zhou14
instagram: ling_zhou

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /blog/page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
